artistas_dict1 = [
    {'name': 'Aleman', channel_id: 'UColfxbsMdfxj8TxBK5Dpdiw'},
    {'name': 'Neto Peña', channel_id: 'UCrq2ArYU6XzMg_uAVPHCE3Q'},
    {'name': 'Santa Fe', channel_id: 'UC4Ge3cqrdyOszmnJTcMICcg'},
    {'name': 'Metrik Vader', channel_id: 'UCOmtNKVF6BM8uNDbJR6D4LQ'},
    {'name': 'CKAN', channel_id: 'UCkD89TEFWsTZluY6tk84yqg'},
    {'name': 'LNGSHT', channel_id: 'UCNKZJqC1BWf2e2D_BIKzS7g'},
    {'name': 'AdanCruz', channel_id: 'UCsNud7A3Vz8X8Pqfw2L2wKg'},
    {'name': 'Sr Marrano', channel_id: 'UC1jqOSFKURb0QR9yErkBHlQ'},
    {'name': 'THRCru2', channel_id: 'UCXCiZmPpHnrAQ1mcfKQYm2A'},
    {'name': 'EptosUno', channel_id: 'UCsjwZJsy9IiykfPbZmYvp1A'},
    {'name': 'Mime 871', channel_id: 'UCcOlDiuXhTuNZlAZOmm21tA'},
    {'name': 'Pato Machete', channel_id: 'UCNVcXV-xZsnHjVxYSMEZROQ'},
    {'name': 'Control Machete', channel_id: 'UC9IzX1jMwTETgdV4WIIEvmQ'},
    {'name': 'Tino El Pinguino', channel_id: 'UCvkIHNuCuQs-JWF12f9TFvA'},
    {'name': 'Boca Floja', channel_id: 'UCACalOr4wnNpTWw9Yyet4Tw'},
    {'name': 'Akil Ammar', channel_id: 'UCUf80veILuNE72TVVGOZITg'},
    {'name': 'West Gold', channel_id: 'UCXlkq2Fxi-aD9kaIPFVRblQ'},
    {'name': 'Robot', channel_id: 'UCliRD7DSeqcuzudajJdWaLg'},
    {'name': 'Dharius', channel_id: 'UCRWeaLWbhoHuHNjxLgG4asQ'},
    {'name': 'Hispana', channel_id: 'UC41ykKNl4Kakh6ISHp0KpVg'},
    {'name': 'Cartel de Santa', channel_id: ''},
    {'name': 'Aczino', channel_id: ''},
    {'name': 'Coko', channel_id: ''},
    {'name': 'Charles Ans', channel_id: ''},
    {'name': 'Gera Mx', channel_id: ''},
    {'name': 'Yoss Bones', channel_id: ''},
    {'name': 'Tabernario', channel_id: ''},
    {'name': 'WK', channel_id: ''},
    {'name': 'Mike Diaz', channel_id: ''},
    {'name': 'Lefty SM', channel_id: ''},
    {'name': 'T-Killa', channel_id: ''},
    {'name': 'Faruz Feet', channel_id: ''},
    {'name': 'Spvce Problems', channel_id: ''},
    {'name': 'Reno 871', channel_id: ''},
    {'name': 'Big Metra', channel_id: ''},
    {'name': 'Achepe', channel_id: ''},
    {'name': 'Santa RM', channel_id: ''},
    {'name': 'Fntxy', channel_id: ''},
    {'name': 'Yoga Fire', channel_id: ''},
    {'name': 'Anexo Leiruk', channel_id: ''},
    {'name': 'Millonario', channel_id: ''},
    {'name': 'Tren Lokote', channel_id: ''},
    {'name': 'El Pinche Mara', channel_id: ''},
    {'name': 'Geassasin', channel_id: ''},
    {'name': 'Logan Hate', channel_id: ''},
    {'name': 'Dracks', channel_id: ''},
    {'name': 'Phyz Eye', channel_id: ''},
    {'name': 'Zaque', channel_id: ''},
    {'name': 'Muthahupa', channel_id: ''},
    {'name': 'Teeam Revolver', channel_id: ''},
    {'name': 'Tiro Loko', channel_id: ''},
    {'name': 'Simspon ahuevo', channel_id: ''},
    {'name': 'Go Golden Junk', channel_id: ''},
    {'name': 'Primero company', channel_id: ''},
    {'name': 'Tanke one', channel_id: ''},
    {'name': 'Gino', channel_id: ''},
    {'name': 'Montebel', channel_id: ''},
    {'name': 'Proof', channel_id: ''},
    {'name': 'Hadrian', channel_id: ''},
    {'name': 'El pinche brujo', channel_id: ''},
    {'name': 'Bull Montana', channel_id: ''},
    {'name': 'Tonnie Rico', channel_id: ''},
    {'name': 'Dasket Rapley', channel_id: ''},
    {'name': 'Little el Crack', channel_id: ''},
    {'name': 'Leazzy', channel_id: ''},
    {'name': 'Rabia Rivera', channel_id: ''},
    {'name': 'Sociedad Cafe', channel_id: ''},
    {'name': 'Turek Hem', channel_id: ''},
    {'name': 'Jay Romero', channel_id: ''},
    {'name': 'Buffon', channel_id: ''},
    {'name': 'Remik', channel_id: ''},
    {'name': 'Toser One', channel_id: ''},
    {'name': 'Under Side', channel_id: ''},
    {'name': 'Mc Davo', channel_id: ''},
    {'name': 'Neto Reyno', channel_id: ''},
    {'name': 'Snow tha product', channel_id: ''},
    {'name': 'Ximbo', channel_id: ''},
    {'name': 'Vikcy MC', channel_id: ''},
    {'name': 'Zimple', channel_id: ''},
    {'name': 'Zxmyr', channel_id: ''},
    {'name': 'Lenin Pena', channel_id: ''},
    {'name': 'Zmoky', channel_id: ''},
    {'name': 'Guero Sosa', channel_id: ''},
    {'name': 'Maythugs', channel_id: ''},
    {'name': 'Lirika Inverza', channel_id: ''},
    {'name': 'Bizor', channel_id: ''},
    {'name': 'Caballeros del plan g', channel_id: ''},
    {'name': 'Don Aereo', channel_id: ''},
    {'name': 'Kosmer', channel_id: ''},
    {'name': 'Doctor Destino', channel_id: ''},
    {'name': 'Danger Ak', channel_id: ''},
    {'name': 'Cozy Cuz', channel_id: ''},
    {'name': 'Maniako', channel_id: ''},
    {'name': 'Kstro MGA', channel_id: ''},
    {'name': 'Cesaranderan', channel_id: ''},
    {'name': 'Perro ZW', channel_id: ''},
    {'name': 'Manicomio Plan', channel_id: ''},
    {'name': 'Nedman Guerrero', channel_id: ''},
    {'name': 'Rhomer', channel_id: ''},
    {'name': 'Kidd M', channel_id: ''},
    {'name': 'Mc Luka', channel_id: ''},
    {'name': 'Skool 77', channel_id: ''},
    {'name': 'Fermin IV', channel_id: ''},
    {'name': 'Gogo Ras', channel_id: ''},
    {'name': 'Dee', channel_id: ''},
    {'name': 'Industria City', channel_id: ''},
    {'name': 'Aguila Sativa', channel_id: ''},
    {'name': 'Masta Quba', channel_id: ''},
    {'name': 'Audry Funk', channel_id: ''},
    {'name': 'Ogarita', channel_id: ''},
    {'name': 'Ballin', channel_id: ''},
    {'name': 'Escuela Sinica', channel_id: ''},
    {'name': 'Mare Advertencia Lirika', channel_id: ''},
    {'name': 'Bobi Bozman', channel_id: ''},
    {'name': 'Fume 871', channel_id: ''},
    {'name': 'Drvgs', channel_id: ''},
    {'name': 'Limbo Lowfi', channel_id: ''},
    {'name': 'Doble P Ache Ene', channel_id: ''},
    {'name': 'Twisted Minded', channel_id: ''},
    {'name': 'Brez', channel_id: ''},
    {'name': 'Carlos Cartoon', channel_id: ''},
    {'name': 'Eric El Niño', channel_id: ''},
    {'name': 'Yak MAg', channel_id: ''},
    {'name': 'Bruno Grasso', channel_id: ''},
    {'name': 'Rapozt Mortem', channel_id: ''},
    {'name': 'Justinani', channel_id: ''},
    {'name': 'Malva', channel_id: ''},
    {'name': 'Menuda Coincidencia', channel_id: ''},
    {'name': 'La Banda Baston', channel_id: ''},
    {'name': 'Jauría Santa', channel_id: ''},
    {'name': 'Solitario Mondragón', channel_id: ''},
    {'name': 'Bipo Montana', channel_id: ''},
    {'name': 'Caporal', channel_id: ''},
    {'name': 'La Santa Grifa', channel_id: ''},
    {'name': 'Playa Matafokas', channel_id: ''},
]